const currenciesArray = [
  {
    code: "AED",
    name: "United Arab Emirates Dirham",
    country: "United Arab Emirates",
    countryCode: "AE",
    symbol: "د.إ",
  },
  {
    code: "AFN",
    name: "Afghan Afghani",
    country: "Afghanistan",
    countryCode: "AF",
    symbol: "؋",
  },
  {
    code: "ALL",
    name: "Albanian Lek",
    country: "Albania",
    countryCode: "AL",
    symbol: "L",
  },
  {
    code: "AMD",
    name: "Armenian Dram",
    country: "Armenia",
    countryCode: "AM",
    symbol: "֏",
  },
  {
    code: "ANG",
    name: "Netherlands Antillean Guilder",
    country: "Curaçao, Sint Maarten",
    countryCode: "CW", // Using CW for Curaçao as primary; SX for Sint Maarten could also apply
    symbol: "ƒ",
  },
  {
    code: "AOA",
    name: "Angolan Kwanza",
    country: "Angola",
    countryCode: "AO",
    symbol: "Kz",
  },
  {
    code: "ARS",
    name: "Argentine Peso",
    country: "Argentina",
    countryCode: "AR",
    symbol: "$",
  },
  {
    code: "AUD",
    name: "Australian Dollar",
    country: "Australia",
    countryCode: "AU",
    symbol: "A$",
  },
  {
    code: "AWG",
    name: "Aruban Florin",
    country: "Aruba",
    countryCode: "AW",
    symbol: "ƒ",
  },
  {
    code: "AZN",
    name: "Azerbaijani Manat",
    country: "Azerbaijan",
    countryCode: "AZ",
    symbol: "₼",
  },
  {
    code: "BAM",
    name: "Bosnia-Herzegovina Convertible Mark",
    country: "Bosnia and Herzegovina",
    countryCode: "BA",
    symbol: "KM",
  },
  {
    code: "BBD",
    name: "Barbadian Dollar",
    country: "Barbados",
    countryCode: "BB",
    symbol: "Bds$",
  },
  {
    code: "BDT",
    name: "Bangladeshi Taka",
    country: "Bangladesh",
    countryCode: "BD",
    symbol: "৳",
  },
  {
    code: "BGN",
    name: "Bulgarian Lev",
    country: "Bulgaria",
    countryCode: "BG",
    symbol: "лв",
  },
  {
    code: "BHD",
    name: "Bahraini Dinar",
    country: "Bahrain",
    countryCode: "BH",
    symbol: ".د.ب",
  },
  {
    code: "BIF",
    name: "Burundian Franc",
    country: "Burundi",
    countryCode: "BI",
    symbol: "FBu",
  },
  {
    code: "BMD",
    name: "Bermudian Dollar",
    country: "Bermuda",
    countryCode: "BM",
    symbol: "$",
  },
  {
    code: "BND",
    name: "Brunei Dollar",
    country: "Brunei",
    countryCode: "BN",
    symbol: "B$",
  },
  {
    code: "BOB",
    name: "Bolivian Boliviano",
    country: "Bolivia",
    countryCode: "BO",
    symbol: "Bs.",
  },
  {
    code: "BRL",
    name: "Brazilian Real",
    country: "Brazil",
    countryCode: "BR",
    symbol: "R$",
  },
  {
    code: "BSD",
    name: "Bahamian Dollar",
    country: "Bahamas",
    countryCode: "BS",
    symbol: "B$",
  },
  {
    code: "BTN",
    name: "Bhutanese Ngultrum",
    country: "Bhutan",
    countryCode: "BT",
    symbol: "Nu.",
  },
  {
    code: "BWP",
    name: "Botswanan Pula",
    country: "Botswana",
    countryCode: "BW",
    symbol: "P",
  },
  {
    code: "BYN",
    name: "Belarusian Ruble",
    country: "Belarus",
    countryCode: "BY",
    symbol: "Br",
  },
  {
    code: "BZD",
    name: "Belize Dollar",
    country: "Belize",
    countryCode: "BZ",
    symbol: "BZ$",
  },
  {
    code: "CAD",
    name: "Canadian Dollar",
    country: "Canada",
    countryCode: "CA",
    symbol: "C$",
  },
  {
    code: "CDF",
    name: "Congolese Franc",
    country: "Democratic Republic of the Congo",
    countryCode: "CD",
    symbol: "FC",
  },
  {
    code: "CHF",
    name: "Swiss Franc",
    country: "Switzerland",
    countryCode: "CH",
    symbol: "CHF",
  },
  {
    code: "CLP",
    name: "Chilean Peso",
    country: "Chile",
    countryCode: "CL",
    symbol: "$",
  },
  {
    code: "CNY",
    name: "Chinese Yuan",
    country: "China",
    countryCode: "CN",
    symbol: "¥",
  },
  {
    code: "COP",
    name: "Colombian Peso",
    country: "Colombia",
    countryCode: "CO",
    symbol: "$",
  },
  {
    code: "CRC",
    name: "Costa Rican Colón",
    country: "Costa Rica",
    countryCode: "CR",
    symbol: "₡",
  },
  {
    code: "CUP",
    name: "Cuban Peso",
    country: "Cuba",
    countryCode: "CU",
    symbol: "$",
  },
  {
    code: "CVE",
    name: "Cape Verdean Escudo",
    country: "Cape Verde",
    countryCode: "CV",
    symbol: "$",
  },
  {
    code: "CZK",
    name: "Czech Koruna",
    country: "Czech Republic",
    countryCode: "CZ",
    symbol: "Kč",
  },
  {
    code: "DJF",
    name: "Djiboutian Franc",
    country: "Djibouti",
    countryCode: "DJ",
    symbol: "Fdj",
  },
  {
    code: "DKK",
    name: "Danish Krone",
    country: "Denmark",
    countryCode: "DK",
    symbol: "kr",
  },
  {
    code: "DOP",
    name: "Dominican Peso",
    country: "Dominican Republic",
    countryCode: "DO",
    symbol: "RD$",
  },
  {
    code: "DZD",
    name: "Algerian Dinar",
    country: "Algeria",
    countryCode: "DZ",
    symbol: "دج",
  },
  {
    code: "EGP",
    name: "Egyptian Pound",
    country: "Egypt",
    countryCode: "EG",
    symbol: "£",
  },
  {
    code: "ERN",
    name: "Eritrean Nakfa",
    country: "Eritrea",
    countryCode: "ER",
    symbol: "Nfk",
  },
  {
    code: "ETB",
    name: "Ethiopian Birr",
    country: "Ethiopia",
    countryCode: "ET",
    symbol: "Br",
  },
  {
    code: "EUR",
    name: "Euro",
    country: "Eurozone",
    countryCode: "FR",
    symbol: "€",
  }, // EU as a general code for Eurozone
  {
    code: "FJD",
    name: "Fijian Dollar",
    country: "Fiji",
    countryCode: "FJ",
    symbol: "FJ$",
  },
  {
    code: "FKP",
    name: "Falkland Islands Pound",
    country: "Falkland Islands",
    countryCode: "FK",
    symbol: "£",
  },
  {
    code: "FOK",
    name: "Faroese Króna",
    country: "Faroe Islands",
    countryCode: "FO",
    symbol: "kr",
  },
  {
    code: "GBP",
    name: "British Pound",
    country: "United Kingdom",
    countryCode: "GB",
    symbol: "£",
  },
  {
    code: "GEL",
    name: "Georgian Lari",
    country: "Georgia",
    countryCode: "GE",
    symbol: "₾",
  },
  {
    code: "GGP",
    name: "Guernsey Pound",
    country: "Guernsey",
    countryCode: "GG",
    symbol: "£",
  },
  {
    code: "GHS",
    name: "Ghanaian Cedi",
    country: "Ghana",
    countryCode: "GH",
    symbol: "₵",
  },
  {
    code: "GIP",
    name: "Gibraltar Pound",
    country: "Gibraltar",
    countryCode: "GI",
    symbol: "£",
  },
  {
    code: "GMD",
    name: "Gambian Dalasi",
    country: "Gambia",
    countryCode: "GM",
    symbol: "D",
  },
  {
    code: "GNF",
    name: "Guinean Franc",
    country: "Guinea",
    countryCode: "GN",
    symbol: "FG",
  },
  {
    code: "GTQ",
    name: "Guatemalan Quetzal",
    country: "Guatemala",
    countryCode: "GT",
    symbol: "Q",
  },
  {
    code: "GYD",
    name: "Guyanese Dollar",
    country: "Guyana",
    countryCode: "GY",
    symbol: "G$",
  },
  {
    code: "HKD",
    name: "Hong Kong Dollar",
    country: "Hong Kong",
    countryCode: "HK",
    symbol: "HK$",
  },
  {
    code: "HNL",
    name: "Honduran Lempira",
    country: "Honduras",
    countryCode: "HN",
    symbol: "L",
  },
  {
    code: "HRK",
    name: "Croatian Kuna",
    country: "Croatia",
    countryCode: "HR",
    symbol: "kn",
  },
  {
    code: "HTG",
    name: "Haitian Gourde",
    country: "Haiti",
    countryCode: "HT",
    symbol: "G",
  },
  {
    code: "HUF",
    name: "Hungarian Forint",
    country: "Hungary",
    countryCode: "HU",
    symbol: "Ft",
  },
  {
    code: "IDR",
    name: "Indonesian Rupiah",
    country: "Indonesia",
    countryCode: "ID",
    symbol: "Rp",
  },
  {
    code: "ILS",
    name: "Israeli New Shekel",
    country: "Israel",
    countryCode: "IL",
    symbol: "₪",
  },
  {
    code: "IMP",
    name: "Manx Pound",
    country: "Isle of Man",
    countryCode: "IM",
    symbol: "£",
  },
  {
    code: "INR",
    name: "Indian Rupee",
    country: "India",
    countryCode: "IN",
    symbol: "₹",
  },
  {
    code: "IQD",
    name: "Iraqi Dinar",
    country: "Iraq",
    countryCode: "IQ",
    symbol: "ع.د",
  },
  {
    code: "IRR",
    name: "Iranian Rial",
    country: "Iran",
    countryCode: "IR",
    symbol: "﷼",
  },
  {
    code: "ISK",
    name: "Icelandic Króna",
    country: "Iceland",
    countryCode: "IS",
    symbol: "kr",
  },
  {
    code: "JEP",
    name: "Jersey Pound",
    country: "Jersey",
    countryCode: "JE",
    symbol: "£",
  },
  {
    code: "JMD",
    name: "Jamaican Dollar",
    country: "Jamaica",
    countryCode: "JM",
    symbol: "J$",
  },
  {
    code: "JOD",
    name: "Jordanian Dinar",
    country: "Jordan",
    countryCode: "JO",
    symbol: "JD",
  },
  {
    code: "JPY",
    name: "Japanese Yen",
    country: "Japan",
    countryCode: "JP",
    symbol: "¥",
  },
  {
    code: "KES",
    name: "Kenyan Shilling",
    country: "Kenya",
    countryCode: "KE",
    symbol: "KSh",
  },
  {
    code: "KGS",
    name: "Kyrgystani Som",
    country: "Kyrgyzstan",
    countryCode: "KG",
    symbol: "с",
  },
  {
    code: "KHR",
    name: "Cambodian Riel",
    country: "Cambodia",
    countryCode: "KH",
    symbol: "៛",
  },
  {
    code: "KID",
    name: "Kiribati Dollar",
    country: "Kiribati",
    countryCode: "KI",
    symbol: "$",
  },
  {
    code: "KMF",
    name: "Comorian Franc",
    country: "Comoros",
    countryCode: "KM",
    symbol: "CF",
  },
  {
    code: "KRW",
    name: "South Korean Won",
    country: "South Korea",
    countryCode: "KR",
    symbol: "₩",
  },
  {
    code: "KWD",
    name: "Kuwaiti Dinar",
    country: "Kuwait",
    countryCode: "KW",
    symbol: "KD",
  },
  {
    code: "KYD",
    name: "Cayman Islands Dollar",
    country: "Cayman Islands",
    countryCode: "KY",
    symbol: "CI$",
  },
  {
    code: "KZT",
    name: "Kazakhstani Tenge",
    country: "Kazakhstan",
    countryCode: "KZ",
    symbol: "₸",
  },
  {
    code: "LAK",
    name: "Laotian Kip",
    country: "Laos",
    countryCode: "LA",
    symbol: "₭",
  },
  {
    code: "LBP",
    name: "Lebanese Pound",
    country: "Lebanon",
    countryCode: "LB",
    symbol: "ل.ل",
  },
  {
    code: "LKR",
    name: "Sri Lankan Rupee",
    country: "Sri Lanka",
    countryCode: "LK",
    symbol: "Rs",
  },
  {
    code: "LRD",
    name: "Liberian Dollar",
    country: "Liberia",
    countryCode: "LR",
    symbol: "L$",
  },
  {
    code: "LSL",
    name: "Lesotho Loti",
    country: "Lesotho",
    countryCode: "LS",
    symbol: "M",
  },
  {
    code: "LYD",
    name: "Libyan Dinar",
    country: "Libya",
    countryCode: "LY",
    symbol: "LD",
  },
  {
    code: "MAD",
    name: "Moroccan Dirham",
    country: "Morocco",
    countryCode: "MA",
    symbol: "DH",
  },
  {
    code: "MDL",
    name: "Moldovan Leu",
    country: "Moldova",
    countryCode: "MD",
    symbol: "L",
  },
  {
    code: "MGA",
    name: "Malagasy Ariary",
    country: "Madagascar",
    countryCode: "MG",
    symbol: "Ar",
  },
  {
    code: "MKD",
    name: "Macedonian Denar",
    country: "North Macedonia",
    countryCode: "MK",
    symbol: "ден",
  },
  {
    code: "MMK",
    name: "Myanmar Kyat",
    country: "Myanmar",
    countryCode: "MM",
    symbol: "K",
  },
  {
    code: "MNT",
    name: "Mongolian Tugrik",
    country: "Mongolia",
    countryCode: "MN",
    symbol: "₮",
  },
  {
    code: "MOP",
    name: "Macanese Pataca",
    country: "Macau",
    countryCode: "MO",
    symbol: "MOP$",
  },
  {
    code: "MRU",
    name: "Mauritanian Ouguiya",
    country: "Mauritania",
    countryCode: "MR",
    symbol: "UM",
  },
  {
    code: "MUR",
    name: "Mauritian Rupee",
    country: "Mauritius",
    countryCode: "MU",
    symbol: "₨",
  },
  {
    code: "MVR",
    name: "Maldivian Rufiyaa",
    country: "Maldives",
    countryCode: "MV",
    symbol: "Rf",
  },
  {
    code: "MWK",
    name: "Malawian Kwacha",
    country: "Malawi",
    countryCode: "MW",
    symbol: "MK",
  },
  {
    code: "MXN",
    name: "Mexican Peso",
    country: "Mexico",
    countryCode: "MX",
    symbol: "$",
  },
  {
    code: "MYR",
    name: "Malaysian Ringgit",
    country: "Malaysia",
    countryCode: "MY",
    symbol: "RM",
  },
  {
    code: "MZN",
    name: "Mozambican Metical",
    country: "Mozambique",
    countryCode: "MZ",
    symbol: "MT",
  },
  {
    code: "NAD",
    name: "Namibian Dollar",
    country: "Namibia",
    countryCode: "NA",
    symbol: "N$",
  },
  {
    code: "NGN",
    name: "Nigerian Naira",
    country: "Nigeria",
    countryCode: "NG",
    symbol: "₦",
  },
  {
    code: "NIO",
    name: "Nicaraguan Córdoba",
    country: "Nicaragua",
    countryCode: "NI",
    symbol: "C$",
  },
  {
    code: "NOK",
    name: "Norwegian Krone",
    country: "Norway",
    countryCode: "NO",
    symbol: "kr",
  },
  {
    code: "NPR",
    name: "Nepalese Rupee",
    country: "Nepal",
    countryCode: "NP",
    symbol: "₨",
  },
  {
    code: "NZD",
    name: "New Zealand Dollar",
    country: "New Zealand",
    countryCode: "NZ",
    symbol: "NZ$",
  },
  {
    code: "OMR",
    name: "Omani Rial",
    country: "Oman",
    countryCode: "OM",
    symbol: "ر.ع.",
  },
  {
    code: "PAB",
    name: "Panamanian Balboa",
    country: "Panama",
    countryCode: "PA",
    symbol: "B/.",
  },
  {
    code: "PEN",
    name: "Peruvian Sol",
    country: "Peru",
    countryCode: "PE",
    symbol: "S/",
  },
  {
    code: "PGK",
    name: "Papua New Guinean Kina",
    country: "Papua New Guinea",
    countryCode: "PG",
    symbol: "K",
  },
  {
    code: "PHP",
    name: "Philippine Peso",
    country: "Philippines",
    countryCode: "PH",
    symbol: "₱",
  },
  {
    code: "PKR",
    name: "Pakistani Rupee",
    country: "Pakistan",
    countryCode: "PK",
    symbol: "₨",
  },
  {
    code: "PLN",
    name: "Polish Zloty",
    country: "Poland",
    countryCode: "PL",
    symbol: "zł",
  },
  {
    code: "PYG",
    name: "Paraguayan Guarani",
    country: "Paraguay",
    countryCode: "PY",
    symbol: "₲",
  },
  {
    code: "QAR",
    name: "Qatari Rial",
    country: "Qatar",
    countryCode: "QA",
    symbol: "QR",
  },
  {
    code: "RON",
    name: "Romanian Leu",
    country: "Romania",
    countryCode: "RO",
    symbol: "lei",
  },
  {
    code: "RSD",
    name: "Serbian Dinar",
    country: "Serbia",
    countryCode: "RS",
    symbol: "дин",
  },
  {
    code: "RUB",
    name: "Russian Ruble",
    country: "Russia",
    countryCode: "RU",
    symbol: "₽",
  },
  {
    code: "RWF",
    name: "Rwandan Franc",
    country: "Rwanda",
    countryCode: "RW",
    symbol: "RF",
  },
  {
    code: "SAR",
    name: "Saudi Riyal",
    country: "Saudi Arabia",
    countryCode: "SA",
    symbol: "SR",
  },
  {
    code: "SBD",
    name: "Solomon Islands Dollar",
    country: "Solomon Islands",
    countryCode: "SB",
    symbol: "SI$",
  },
  {
    code: "SCR",
    name: "Seychellois Rupee",
    country: "Seychelles",
    countryCode: "SC",
    symbol: "₨",
  },
  {
    code: "SDG",
    name: "Sudanese Pound",
    country: "Sudan",
    countryCode: "SD",
    symbol: "SD",
  },
  {
    code: "SEK",
    name: "Swedish Krona",
    country: "Sweden",
    countryCode: "SE",
    symbol: "kr",
  },
  {
    code: "SGD",
    name: "Singapore Dollar",
    country: "Singapore",
    countryCode: "SG",
    symbol: "S$",
  },
  {
    code: "SHP",
    name: "Saint Helena Pound",
    country: "Saint Helena",
    countryCode: "SH",
    symbol: "£",
  },
  {
    code: "SLL",
    name: "Sierra Leonean Leone",
    country: "Sierra Leone",
    countryCode: "SL",
    symbol: "Le",
  },
  {
    code: "SOS",
    name: "Somali Shilling",
    country: "Somalia",
    countryCode: "SO",
    symbol: "Sh",
  },
  {
    code: "SRD",
    name: "Surinamese Dollar",
    country: "Suriname",
    countryCode: "SR",
    symbol: "$",
  },
  {
    code: "SSP",
    name: "South Sudanese Pound",
    country: "South Sudan",
    countryCode: "SS",
    symbol: "£",
  },
  {
    code: "STN",
    name: "São Tomé and Príncipe Dobra",
    country: "São Tomé and Príncipe",
    countryCode: "ST",
    symbol: "Db",
  },
  {
    code: "SYP",
    name: "Syrian Pound",
    country: "Syria",
    countryCode: "SY",
    symbol: "LS",
  },
  {
    code: "SZL",
    name: "Swazi Lilangeni",
    country: "Eswatini",
    countryCode: "SZ",
    symbol: "E",
  },
  {
    code: "THB",
    name: "Thai Baht",
    country: "Thailand",
    countryCode: "TH",
    symbol: "฿",
  },
  {
    code: "TJS",
    name: "Tajikistani Somoni",
    country: "Tajikistan",
    countryCode: "TJ",
    symbol: "SM",
  },
  {
    code: "TMT",
    name: "Turkmenistani Manat",
    country: "Turkmenistan",
    countryCode: "TM",
    symbol: "m",
  },
  {
    code: "TND",
    name: "Tunisian Dinar",
    country: "Tunisia",
    countryCode: "TN",
    symbol: "DT",
  },
  {
    code: "TOP",
    name: "Tongan Paʻanga",
    country: "Tonga",
    countryCode: "TO",
    symbol: "T$",
  },
  {
    code: "TRY",
    name: "Turkish Lira",
    country: "Turkey",
    countryCode: "TR",
    symbol: "₺",
  },
  {
    code: "TTD",
    name: "Trinidad and Tobago Dollar",
    country: "Trinidad and Tobago",
    countryCode: "TT",
    symbol: "TT$",
  },
  {
    code: "TVD",
    name: "Tuvaluan Dollar",
    country: "Tuvalu",
    countryCode: "TV",
    symbol: "$",
  },
  {
    code: "TWD",
    name: "New Taiwan Dollar",
    country: "Taiwan",
    countryCode: "TW",
    symbol: "NT$",
  },
  {
    code: "TZS",
    name: "Tanzanian Shilling",
    country: "Tanzania",
    countryCode: "TZ",
    symbol: "TSh",
  },
  {
    code: "UAH",
    name: "Ukrainian Hryvnia",
    country: "Ukraine",
    countryCode: "UA",
    symbol: "₴",
  },
  {
    code: "UGX",
    name: "Ugandan Shilling",
    country: "Uganda",
    countryCode: "UG",
    symbol: "USh",
  },
  {
    code: "USD",
    name: "United States Dollar",
    country: "United States",
    countryCode: "US",
    symbol: "$",
  },
  {
    code: "UYU",
    name: "Uruguayan Peso",
    country: "Uruguay",
    countryCode: "UY",
    symbol: "$U",
  },
  {
    code: "UZS",
    name: "Uzbekistani Som",
    country: "Uzbekistan",
    countryCode: "UZ",
    symbol: "сўм",
  },
  {
    code: "VES",
    name: "Venezuelan Bolívar",
    country: "Venezuela",
    countryCode: "VE",
    symbol: "Bs.",
  },
  {
    code: "VND",
    name: "Vietnamese Dong",
    country: "Vietnam",
    countryCode: "VN",
    symbol: "₫",
  },
  {
    code: "VUV",
    name: "Vanuatu Vatu",
    country: "Vanuatu",
    countryCode: "VU",
    symbol: "VT",
  },
  {
    code: "WST",
    name: "Samoan Tala",
    country: "Samoa",
    countryCode: "WS",
    symbol: "WS$",
  },
  {
    code: "XAF",
    name: "Central African CFA Franc",
    country: "CEMAC",
    countryCode: "CM", // Using CM (Cameroon) as a representative; multiple countries use XAF
    symbol: "FCFA",
  },
  {
    code: "XCD",
    name: "Eastern Caribbean Dollar",
    country: "OECS",
    countryCode: "AG", // Using AG (Antigua and Barbuda) as a representative; multiple countries use XCD
    symbol: "EC$",
  },
  {
    code: "XDR",
    name: "Special Drawing Rights",
    country: "International Monetary Fund",
    countryCode: "XX", // No official country code; using XX as placeholder
    symbol: "SDR",
  },
  {
    code: "XOF",
    name: "West African CFA Franc",
    country: "UEMOA",
    countryCode: "SN", // Using SN (Senegal) as a representative; multiple countries use XOF
    symbol: "CFA",
  },
  {
    code: "XPF",
    name: "CFP Franc",
    country: "French Pacific Territories",
    countryCode: "PF", // Using PF (French Polynesia) as a representative
    symbol: "₣",
  },
  {
    code: "YER",
    name: "Yemeni Rial",
    country: "Yemen",
    countryCode: "YE",
    symbol: "﷼",
  },
  {
    code: "ZAR",
    name: "South African Rand",
    country: "South Africa",
    countryCode: "ZA",
    symbol: "R",
  },
  {
    code: "ZMW",
    name: "Zambian Kwacha",
    country: "Zambia",
    countryCode: "ZM",
    symbol: "ZK",
  },
  {
    code: "ZWL",
    name: "Zimbabwean Dollar",
    country: "Zimbabwe",
    countryCode: "ZW",
    symbol: "Z$",
  },
];
//
let dollarRateArray = ["INR", "EUR", "JPY", "GBP", "AUD", "CAD", "CHF", "CNY"];
